---
name: Data-NDS
version: 3.10
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
abstract: routines to work with a perl nested data structure
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Algorithm::Permute: 0
  IO::File: 0
  Storable: 0
  perl: 5.6.0
provides:
  Data::NDS:
    file: lib/Data/NDS.pm
    version: 3.10
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
